### PR TITLE
Fix: remove null_data_sources

### PR DESCRIPTION
**Pull request by AgustinRamiroDiaz**
# Fixes https://github.com/terraform-google-modules/terraform-google-event-function/issues/182

# Changes proposed
Remove usages of `null_data_source` and address the impact accordingly, preserving the configuration values and the `depends_on` 

This should not make any modification in behavior

# Testing done
I've run applies that created, deleted and updated the resources using [my fork module](https://github.com/AgustinRamiroDiaz/terraform-google-scheduled-function/tree/feature/change-event-function-branch) which points to this branch

All plans were successful and the resources were correctly applied in GCP

### CODE REVIEW

**Comment by AgustinRamiroDiaz** [comment]
Is there something I can do to help this PR get reviewed?

**Comment by AgustinRamiroDiaz** [comment]
Remove stale label

**Review by bharathkkb — APPROVED** [review]
Sorry for the delay and thanks for the PR @AgustinRamiroDiaz

**Pull request merged**
