### PR TITLE
fix: use variable to set output file mode on archive file data

### PR DESCRIPTION
**Pull request by spoukke**
This is a proposed fix for [issue #105 ](https://github.com/terraform-google-modules/terraform-google-event-function/issues/105).

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@spoukke
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.PTRIb1J75p/generate_docs/workspace/README.md
55a56
> | archive\_output\_file\_mode | The file mode of the locally generated archive | `string` | `"0664"` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
╷
│
 
Warning: 
Deprecated Resource
│
 
│
 
  with data.null_data_source.wait_for_files,
│
 
  on main.tf line 42, in data "null_data_source" "wait_for_files":
│
 
  42: data "null_data_source" "wait_for_files" 
{
│
 
│
 
The null_data_source was historically used to construct intermediate values
│
 
to re-use elsewhere in configuration, the same can now be achieved using
│
 
locals
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/automatic-labelling-folder
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./examples/automatic-labelling-from-localhost
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./examples/automatic-labelling-from-repository
Success!
 The configuration is valid.
terraform_validate ./examples/delete-vms-without-cmek
╷
│
 
Warning: 
Deprecated Resource
│
 
│
 
  with module.localhost_function.data.null_data_source.wait_for_files,
│
 
  on ../../main.tf line 42, in data "null_data_source" "wait_for_files":
│
 
  42: data "null_data_source" "wait_for_files" 
{
│
 
│
 
The null_data_source was historically used to construct intermediate values
│
 
to re-use elsewhere in configuration, the same can now be achieved using
│
 
locals
╵
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./examples/dynamic-files
╷
│
 
Warning: 
Deprecated Resource
│
 
│
 
  with module.localhost_function.data.null_data_source.wait_for_files,
│
 
  on ../../main.tf line 42, in data "null_data_source" "wait_for_files":
│
 
  42: data "null_data_source" "wait_for_files" 
{
│
 
│
 
The null_data_source was historically used to construct intermediate values
│
 
to re-use elsewhere in configuration, the same can now be achieved using
│
 
locals
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./modules/event-folder-log-entry
Success!
 The configuration is valid.
terraform_validate ./modules/event-project-log-entry
Success!
 The configuration is valid.
terraform_validate ./modules/repository-function
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/automatic-labelling-folder
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./test/setup
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on versions.tf line 22, in provider "google":
│
 
  22:   version = 
"~> 3.53.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
 ```

**Comment by comment-bot-dev** [comment]
@spoukke
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
╷
│
 
Warning: 
Deprecated Resource
│
 
│
 
  with data.null_data_source.wait_for_files,
│
 
  on main.tf line 42, in data "null_data_source" "wait_for_files":
│
 
  42: data "null_data_source" "wait_for_files" 
{
│
 
│
 
The null_data_source was historically used to construct intermediate values
│
 
to re-use elsewhere in configuration, the same can now be achieved using
│
 
locals
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./examples/automatic-labelling-folder
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./examples/automatic-labelling-from-localhost
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./examples/automatic-labelling-from-repository
Success!
 The configuration is valid.
terraform_validate ./examples/delete-vms-without-cmek
╷
│
 
Warning: 
Deprecated Resource
│
 
│
 
  with module.localhost_function.data.null_data_source.wait_for_files,
│
 
  on ../../main.tf line 42, in data "null_data_source" "wait_for_files":
│
 
  42: data "null_data_source" "wait_for_files" 
{
│
 
│
 
The null_data_source was historically used to construct intermediate values
│
 
to re-use elsewhere in configuration, the same can now be achieved using
│
 
locals
╵
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./examples/dynamic-files
╷
│
 
Warning: 
Deprecated Resource
│
 
│
 
  with module.localhost_function.data.null_data_source.wait_for_files,
│
 
  on ../../main.tf line 42, in data "null_data_source" "wait_for_files":
│
 
  42: data "null_data_source" "wait_for_files" 
{
│
 
│
 
The null_data_source was historically used to construct intermediate values
│
 
to re-use elsewhere in configuration, the same can now be achieved using
│
 
locals
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./modules/event-folder-log-entry
Success!
 The configuration is valid.
terraform_validate ./modules/event-project-log-entry
Success!
 The configuration is valid.
terraform_validate ./modules/repository-function
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/automatic-labelling-folder
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../../main.tf line 59, in data "archive_file" "main":
│
 
  59:   
output_file_mode
 = var.archive_output_file_mode
│
 
│
 
An argument named "output_file_mode" is not expected here.
╵
terraform_validate ./test/setup
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on versions.tf line 22, in provider "google":
│
 
  22:   version = 
"~> 3.53.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
│
 
│
 
(and one more similar warning elsewhere)
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
 ```

**Comment by comment-bot-dev** [comment]
@spoukke
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by spoukke** [comment]
I don't know what is the issue with the workflow, could I have some information about it ?

**Pull request closed without merging**
